[package]
name = "migrator"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)', 'cfg(target_os, values("solana"))'] }

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = { workspace = true }
pinocchio-log = { workspace = true }
pinocchio-system = { workspace = true }
pinocchio-token = { workspace = true }
solana-address = { workspace = true }

[features]
default = []
no-entrypoint = []

[dev-dependencies]
litesvm = "0.9"
mollusk-svm = { version = "0.11.0", features = ["fuzz", "inner-instructions"] }
mollusk-svm-programs-token = { version = "0.11.0", default-features = false, features = ["token", "associated-token"] }
solana-account = "3.0"
solana-address = { workspace = true }
solana-instruction = "3.1"
solana-keypair = "3.1"
solana-message = "~3.0"
solana-program-option = "3.1.0"
solana-program-pack = "3.0"
solana-program = { workspace = true }
solana-program-error = "3.0"
solana-pubkey = "3.0"
solana-rent = "3.0"
solana-signer = "3.0"
solana-transaction-error = "~3.0"
solana-transaction = { version = "~3.0", features = ["verify"] }
spl-token-interface = "2.0.0"
